### PR TITLE
Add hyperspecific rules directory

### PR DESCRIPTION
**Pull request by josephmturner**
Contains the changes discussed in #7. I did not add `11-12.diff` (I wasn't sure what would be the best way to generate the diff - I'd be grateful to learn how you do it)

To get the changes made to the wiki, run `git clone https://github.com/josephmturner/full-fledged-hledger.wiki.git` (as I understand it, there's no way to make a PR for changes made to a wiki repo)

NB:
- I replaced `Just [_, basename] = filePattern "**/*.journal" file` with `let basename = takeBaseName file` in the extraDeps function
- When I ran the export script inside `12-hyperspecific-rules/`, it reformatted many of the reports inside `exports/`. Keep this in mind when generating `11-12.diff`

### CODE REVIEW

**Comment by adept** [comment]
I am going to merge this and change it a bit, if you don't mind. I think "per-file" or "file-specific rules" would be a better description, for instance...

**Comment by adept** [comment]
Oh, and it terms of regenerating everything: the easiest way, perhaps, is to run `./docker.sh`, and then from  there run `./rebuild.sh` and `./updatediffs.sh`

**Comment by adept** [comment]
Thank you very much, it is all merged in now!

**Comment by josephmturner** [comment]
That's wonderful! I'm glad I could help out.

I agree, 'file-specific' is more accurately descriptive than 'hyperspecific'. The other phrasing changes you made look great as well.

See you around, friend.

**Pull request merged**
